
usuarios = [
    {'nombre': 'Ana', 'apellido': 'García', 'edad': 25, 'estado': 'activo', 'email': 'ana.garcia@example.com', 'contrasena': 'contrasena123'},
    {'nombre': 'Luis', 'apellido': 'Martínez', 'edad': 30, 'estado': 'activo', 'email': 'luis.martinez@example.com', 'contrasena': 'password456'},
    {'nombre': 'María', 'apellido': 'López', 'edad': 22, 'estado': 'inactivo', 'email': 'maria.lopez@example.com', 'contrasena': 'marialopez789'},
    {'nombre': 'Carlos', 'apellido': 'Pérez', 'edad': 35, 'estado': 'activo', 'email': 'carlos.perez@example.com', 'contrasena': 'carlosperez'},
    {'nombre': 'Elena', 'apellido': 'Hernández', 'edad': 28, 'estado': 'activo', 'email': 'elena.hernandez@example.com', 'contrasena': 'elena4567'},
    {'nombre': 'Jorge', 'apellido': 'Sánchez', 'edad': 31, 'estado': 'inactivo', 'email': 'jorge.sanchez@example.com', 'contrasena': 'jsanchez123'},
    {'nombre': 'Lucía', 'apellido': 'Ramírez', 'edad': 20, 'estado': 'activo', 'email': 'lucia.ramirez@example.com', 'contrasena': 'lucia987'},
    {'nombre': 'Pedro', 'apellido': 'Torres', 'edad': 40, 'estado': 'activo', 'email': 'pedro.torres@example.com', 'contrasena': 'pedrotorres1'},
    {'nombre': 'Claudia', 'apellido': 'Vásquez', 'edad': 18, 'estado': 'inactivo', 'email': 'claudia.vasquez@example.com', 'contrasena': 'claudia456'},
    {'nombre': 'Raúl', 'apellido': 'Morales', 'edad': 34, 'estado': 'activo', 'email': 'raul.morales@example.com', 'contrasena': 'raulm789'},
    {'nombre': 'Sara', 'apellido': 'Reyes', 'edad': 27, 'estado': 'activo', 'email': 'sara.reyes@example.com', 'contrasena': 'sara1234'},
    {'nombre': 'Diego', 'apellido': 'Ortega', 'edad': 32, 'estado': 'inactivo', 'email': 'diego.ortega@example.com', 'contrasena': 'diego5678'},
    {'nombre': 'Valeria', 'apellido': 'Cruz', 'edad': 24, 'estado': 'activo', 'email': 'valeria.cruz@example.com', 'contrasena': 'valeria987'},
    {'nombre': 'Sofía', 'apellido': 'Ramos', 'edad': 19, 'estado': 'activo', 'email': 'sofia.ramos@example.com', 'contrasena': 'sofia1234'},
    {'nombre': 'Andrés', 'apellido': 'Gutiérrez', 'edad': 33, 'estado': 'inactivo', 'email': 'andres.gutierrez@example.com', 'contrasena': 'andres5678'},
    {'nombre': 'Paula', 'apellido': 'Mendoza', 'edad': 21, 'estado': 'activo', 'email': 'paula.mendoza@example.com', 'contrasena': 'paula987'},
    {'nombre': 'Fernando', 'apellido': 'Romero', 'edad': 29, 'estado': 'activo', 'email': 'fernando.romero@example.com', 'contrasena': 'fernando1'},
    {'nombre': 'Natalia', 'apellido': 'Vargas', 'edad': 26, 'estado': 'activo', 'email': 'natalia.vargas@example.com', 'contrasena': 'natalia123'},
    {'nombre': 'Gonzalo', 'apellido': 'Rojas', 'edad': 41, 'estado': 'inactivo', 'email': 'gonzalo.rojas@example.com', 'contrasena': 'gonzalo456'},
    {'nombre': 'Marta', 'apellido': 'Flores', 'edad': 23, 'estado': 'activo', 'email': 'marta.flores@example.com', 'contrasena': 'marta789'},
    {'nombre': 'David', 'apellido': 'Silva', 'edad': 35, 'estado': 'activo', 'email': 'david.silva@example.com', 'contrasena': 'davidsilva'},
    {'nombre': 'Laura', 'apellido': 'Castro', 'edad': 30, 'estado': 'inactivo', 'email': 'laura.castro@example.com', 'contrasena': 'laura4567'},
    {'nombre': 'Gabriel', 'apellido': 'Rubio', 'edad': 37, 'estado': 'activo', 'email': 'gabriel.rubio@example.com', 'contrasena': 'gabriel123'},
    {'nombre': 'Irene', 'apellido': 'Núñez', 'edad': 22, 'estado': 'activo', 'email': 'irene.nunez@example.com', 'contrasena': 'irene789'},
    {'nombre': 'Ricardo', 'apellido': 'Blanco', 'edad': 44, 'estado': 'inactivo', 'email': 'ricardo.blanco@example.com', 'contrasena': 'ricardo1234'},
    {'nombre': 'Carmen', 'apellido': 'Molina', 'edad': 19, 'estado': 'activo', 'email': 'carmen.molina@example.com', 'contrasena': 'carmen5678'},
    {'nombre': 'Manuel', 'apellido': 'Suárez', 'edad': 39, 'estado': 'activo', 'email': 'manuel.suarez@example.com', 'contrasena': 'manuel123'},
    {'nombre': 'Isabel', 'apellido': 'Ibáñez', 'edad': 28, 'estado': 'activo', 'email': 'isabel.ibanez@example.com', 'contrasena': 'isabel789'},
    {'nombre': 'Javier', 'apellido': 'Lara', 'edad': 42, 'estado': 'inactivo', 'email': 'javier.lara@example.com', 'contrasena': 'javier4567'},
    {'nombre': 'Mónica', 'apellido': 'Álvarez', 'edad': 25, 'estado': 'activo', 'email': 'monica.alvarez@example.com', 'contrasena': 'monica1234'},
    {'nombre': 'Pablo', 'apellido': 'Giménez', 'edad': 38, 'estado': 'activo', 'email': 'pablo.gimenez@example.com', 'contrasena': 'pablo5678'},
    {'nombre': 'Rosa', 'apellido': 'Soto', 'edad': 29, 'estado': 'inactivo', 'email': 'rosa.soto@example.com', 'contrasena': 'rosa123'},
    {'nombre': 'Ángel', 'apellido': 'Aguilar', 'edad': 45, 'estado': 'activo', 'email': 'angel.aguilar@example.com', 'contrasena': 'angel789'},
    {'nombre': 'Patricia', 'apellido': 'Fuentes', 'edad': 33, 'estado': 'activo', 'email': 'patricia.fuentes@example.com', 'contrasena': 'patricia1234'},
    {'nombre': 'Tomás', 'apellido': 'López', 'edad': 31, 'estado': 'inactivo', 'email': 'tomas.lopez@example.com', 'contrasena': 'tomas4567'},
    {'nombre': 'Marisol', 'apellido': 'Campos', 'edad': 24, 'estado': 'activo', 'email': 'marisol.campos@example.com', 'contrasena': 'marisol567'},
    {'nombre': 'Ignacio', 'apellido': 'Vega', 'edad': 35, 'estado': 'activo', 'email': 'ignacio.vega@example.com', 'contrasena': 'ignacio123'},
    {'nombre': 'Beatriz', 'apellido': 'Peña', 'edad': 21, 'estado': 'activo', 'email': 'beatriz.pena@example.com', 'contrasena': 'beatriz789'},
    {'nombre': 'Francisco', 'apellido': 'Herrera', 'edad': 27, 'estado': 'inactivo', 'email': 'francisco.herrera@example.com', 'contrasena': 'francisco456'},
    {'nombre': 'Julia', 'apellido': 'Reyes', 'edad': 32, 'estado': 'activo', 'email': 'julia.reyes@example.com', 'contrasena':'julia5678'}
]

